### ISSUE TITLE
Sample projects duplicate themselves

### ISSUE THREAD

**Issue by rowanthemodder** [Ttanasart-pt/Pixel-Composer#1]
# Steps to reproduce
- Open a sample project.
- Go to File -> New
- Should duplicate all visible sample projects in the viewer
# Expected behavior
Sample projects should stay unchanged.
# Versions
- Pixel Composer 8.1
- Windows 10
# Additional notes
Installed with the itch.io app, app is located in C:/Users/USR/AppData/Roaming/itch/apps/pixel-composer/
Possibly a permissions issue related to installation location? Unsure, not very familiar with windows.

**Comment by Ttanasart-pt** [comment]
This one should be fixed on 0.8.2. I just forget to clear the sample project list on app restart.

**Comment by Ttanasart-pt** [comment]
Fixed in release 0.8.2
