### ISSUE TITLE
[BUG] [DEMO] Crash when loading tutorials

### ISSUE THREAD

**Issue by Ttanasart-pt** [Ttanasart-pt/Pixel-Composer#11]
**Log message**
ERROR in

action number 1

of Draw Event

for object o_main:

I32 argument is undefined############################################################################################

gml_Script_anon_Panel_Inspector_gml_GlobalScript_panel_inspector_100155_Panel_Inspector_gml_GlobalScript_panel_inspector (line 104)

gml_Script_anon_scrollPane_gml_GlobalScript_scrollPane_698475_scrollPane_gml_GlobalScript_scrollPane (line 46)

gml_Script_drawContent_Panel_Inspector_gml_GlobalScript_panel_inspector (line 429)

gml_Script_draw_PanelContent_gml_GlobalScript_panel_data (line 444)

gml_Script_drawPanel_Panel_gml_GlobalScript_panel_data (line 361)

gml_Script_draw_Panel_gml_GlobalScript_panel_data (line 297)

gml_Script_draw_Panel_gml_GlobalScript_panel_data (line 313)

gml_Script_draw_Panel_gml_GlobalScript_panel_data (line 313)

gml_Object_o_main_Draw_64 (line 4)

**Describe the bug**
Every time I have a tutorial opened and try to open another one the program crashes. I tried to replicate the error and it only happens if I have a node double clicked for preview:

**Comment by Ttanasart-pt** [comment]
Link to report [itch](https://itch.io/t/2552136/crash-when-loading-tutorialsdemo-version)

**Comment by Ttanasart-pt** [comment]
Fix in demo.10.3

**Comment by inxomnyaa** [comment]
I didn't feel like opening a new issue, since this is closely related - The demos won't open at all in v. 1.18.0.4 Steam (probably, not sure if the demo has other versioning) which made it quite hard to check out & understand how the app even works
