### ISSUE TITLE
[Bug] - Transparency in Masks Breaks Blend Nodes

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#14]
When a surface output using transparency is connected to a `Blend` node's mask input, the blend node breaks and produces a malformed output. This was seen in `v 1.0.7`.

I was able to get around this using a `Color Replace` node and setting all other colors to black. Disabling that option will again produce malformed blend outputs.

*Error:*
![image](https://user-images.githubusercontent.com/6645950/209887263-c8b9569c-aee4-4da0-8106-3f4d2106e0f4.png)

*Expected:*
![image](https://user-images.githubusercontent.com/6645950/209887227-049f5526-4db8-4e5b-9d39-c8449eeb2ef9.png)

**Comment by Synthoid** [comment]
To further clarify, my expectation is that transparent or clear pixels would be treated as black during mask operations.

**Comment by Ttanasart-pt** [comment]
Okay, so it seems like it samples only the RGB channel. I'll change it to multiply alpha too in the next version. Thank you.

**Comment by Ttanasart-pt** [comment]
Multiply alpha in blend node is added in 1.0.8.
