### ISSUE TITLE
[Enhancement] - GIF Export Culls Partially Transparent Pixels

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#16]
When exporting to an animated `GIF` any pixels that are partially transparent seem to be culled entirely. I know that `GIF` doesn't support partial transparency, but I would expect the partially transparent textures to just have their alpha set to 1 instead of being culled. It could be that this is something already controlled in the `Export` node that I'm not aware of?

![image](https://user-images.githubusercontent.com/6645950/209892855-21a3a1e7-efb1-4627-8a5b-8a2fcee4d4ea.png)

***Transparent:***
![RainbowRunTransparent](https://user-images.githubusercontent.com/6645950/209892870-40bfffc2-495c-4d84-8247-c15db5c4bbf1.gif)

***Solid:***
![RainbowRunSolid](https://user-images.githubusercontent.com/6645950/209892877-3e8ce130-c544-4b4e-8534-01ee9436b86e.gif)

**Comment by Ttanasart-pt** [comment]
I used ImageMagick for gif conversion, and their option for dealing with alpha is limited. I think I can add nodes for dealing with alpha such as threshold or dithering in the next version.

**Comment by Synthoid** [comment]
That sounds like a good solution. This isn't a massive issue, but I wanted to note it since `GIF` export is very useful for showing off Pixel Composer's animation support.

**Comment by Ttanasart-pt** [comment]
Alpha threshold and dithering added in 1.0.8
