### ISSUE TITLE
[Enhancement] - (1.0.7) - Export Result Issues

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#17]
When exporting an animated `GIF`, the first frame's duration seems to be drastically shorter than the others. This may just be a limitation of the GIF exporter as GIF files are always a little wonky when looping. The preview image for the GIF shows the correct first frame, but playing the GIF seems to almost remove the first frame. If you blink at just the right time your brain can actually register the first frame and it is rendered as expected. Not sure if this is actually something that can be resolved, or if users should just have the first two/first and last frames be the same.

***Preview Thumbnail:***
![image](https://user-images.githubusercontent.com/6645950/209987918-8bd80409-7b08-477e-bdf3-e159007766b4.png)

***Exported GIF:***
![RainbowRunSolid](https://user-images.githubusercontent.com/6645950/209987850-76b8cbb0-e3ef-4fde-898d-36c6b1b24e40.gif)

***First Frame of Exported Image Sequence:***
![RainbowRun00](https://user-images.githubusercontent.com/6645950/209987965-86779d41-fc61-48fc-89c8-5932942f76e0.png)

**Comment by Synthoid** [comment]
Related. When exporting an image sequence, the exported images seem to iterate through an animation's frames and export multiple versions of the same sprite before moving onto the next index. Is this the expected behavior when exporting with an animated value? (see `Composer View` below) I've exported an image sequence before and did not run into this issue so I wasn't sure. My expectation was it would only export the same frames used in the above `GIF` animation.

***Image Sequence Output:***
![image](https://user-images.githubusercontent.com/6645950/209989384-186584b1-7a11-4570-9245-6d47df6bbb3b.png)

***Expected and Unexpected Sprites:***
![image](https://user-images.githubusercontent.com/6645950/209989556-d2c45664-ca92-4327-ab45-297771d2496c.png)

***Composer View:***
![image](https://user-images.githubusercontent.com/6645950/209989940-f28083d0-cc2c-429f-9e7d-c23aa47091f8.png)

**Comment by Ttanasart-pt** [comment]
I'll take a closer look at the gif exporter to see what caused the problem. 

For the second post, I noticed you've created an image array on the solid node (notice a different-looking junction). I presume you use a palette as a color input, a palette is an array of colors. If you want to select a single color from the array, you should use the "array get" node after the palette node.

![path](https://user-images.githubusercontent.com/22589759/210027963-3a473c9e-eed4-49ad-a63e-ffbd57762088.png)

When exporting image sequence of image array, the program will go through each image in the array per each frame. So the output you get is expected.

**Comment by Synthoid** [comment]
Ah, I see! (And good guess on the palette) Converting that section to use the `Array Get` node did indeed remove the extra frames during the export process. Thanks!

![image](https://user-images.githubusercontent.com/6645950/210109527-05e97891-ee01-4e5f-8f85-73f48bc7a48d.png)

Curiously, the last sprite frame is sampled incorrectly now and seems to be a duplicate of the second to last sprite frame:

![image](https://user-images.githubusercontent.com/6645950/210109604-b82cbf81-50a0-4628-a5da-07178e90ef5e.png)

The last frame (8) should look like this:

![image](https://user-images.githubusercontent.com/6645950/210109644-4df66c69-4729-49cd-b519-7217f9aaa0f1.png)

But instead it seems to use the correct shadow color on the previous sprite frame (7):

![image](https://user-images.githubusercontent.com/6645950/210109745-bf28d45c-38c2-486d-9fbd-989be9d304fd.png)

**Comment by Ttanasart-pt** [comment]
I check the source code and it should be right. When you animated the index value, do you end at 7 or 8?

**Comment by Synthoid** [comment]
This issue is still present as of `1.0.9`. The index value starts at frame 1 (value 0) and ends at frame 8 (value 7) as seen below. All of the previews in the node area look correct and generating a sprite sheet shows the expected values as well so I'm guessing this is specifically related to image sequence exporting.

***Frame 1***
![image](https://user-images.githubusercontent.com/6645950/211205011-202c2172-1838-4409-bd6b-b3720517a413.png)

***Frame 8***
![image](https://user-images.githubusercontent.com/6645950/211205031-ac91f5f4-ec5b-4545-9383-cf4fb5924eb4.png)

**Comment by Ttanasart-pt** [comment]
Hm... can you send me the project file and the image you use for further analysis. I checked with my own image and it seem to work as expected. Thank you.

![Screenshot 2023-01-10 120700](https://user-images.githubusercontent.com/22589759/211466590-1a17f2d7-01e9-4f4d-bc58-0bfa8f55fd45.png)

**Comment by Synthoid** [comment]
I made a slightly more streamlined project and still ran into the issue. Maybe it's a certain combination of nodes? I've included the test sprite sheet and the `.pxc` file (as a `txt`) below.

![NumRun](https://user-images.githubusercontent.com/6645950/211676664-40741b0b-2425-4e51-aea4-520f01abfcc3.png)
[NumRainbow.txt](https://github.com/Ttanasart-pt/Pixel-Composer/files/10387312/NumRainbow.txt)

**Comment by Ttanasart-pt** [comment]
Okay, I found the bug now. This should be fix in the next version. Thank you for reporting.

**Comment by Synthoid** [comment]
Confirming that this is fixed as of `1.1.0`

![image](https://user-images.githubusercontent.com/6645950/213071390-890d1332-a965-4ce2-a0f4-33e6a5c861cd.png)
