### ISSUE TITLE
[Bug] (1.0.7) - Sprite Sheet Node Skips First Animation Frame

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#19]
When generating a sprite sheet with the `Sheet` node I noticed the sequence of the sprites depends on the current frame of the animation timeline. If the timeline is set to the first frame, the first cell of the generated sprite sheet will be blank. If the timeline is set to any other frame the sprite sheet will start with that frame's sprite then loop through all the other frames correctly.

Additionally, I noticed that the shadows were not being included in the sprite sheet for some reason. Padding and other modifications like the dithering overlay seem to make it in so it's not just pulling the original sampled sprites. Not sure what is going on there.

***Original Sprites:***
![image](https://user-images.githubusercontent.com/6645950/210151560-27d7ba84-a224-4056-af9f-73ad77abda01.png)

***Sheet Generated By Starting Animation At Frame 1:***
![image](https://user-images.githubusercontent.com/6645950/210151621-43e4b128-4a16-4570-9d8d-cdf8280f69df.png)

***Exported File Starting At Frame 7 (of 8):***
![RainbowRunSheet](https://user-images.githubusercontent.com/6645950/210151533-82e59c26-2d9d-4e91-a733-40bfe635d52f.png)

***Pixel Composer:***
![image](https://user-images.githubusercontent.com/6645950/210151710-84f71c8c-1e21-4ff8-91df-62153084d721.png)

**Comment by Ttanasart-pt** [comment]
Thanks for reporting. I did fix the first frame not rendering. For the shadow problem I'm not sure what happened here as I can't replicate it on my device. Can you show me the full node or save file?

**Comment by Synthoid** [comment]
Sure! Here's a screenshot of the full node setup:

![image](https://user-images.githubusercontent.com/6645950/210178508-ee4fbd9b-5402-490e-92c6-7d1b5dad11d0.png)

And the save file (I had to convert it to a `.txt` to upload, but you should be able to just change it back to a `.pxc`):
[RunRainbow.txt](https://github.com/Ttanasart-pt/Pixel-Composer/files/10329108/RunRainbow.txt)

**Comment by Ttanasart-pt** [comment]
![Screenshot 2023-01-02 090736](https://user-images.githubusercontent.com/22589759/210190780-c8af32db-7092-4615-bd58-8b5bca1af836.png)

I check your save and found no shadow missing problem. Maybe the first frame fix also fix this one? I'm not sure you might want to check again once I release 1.0.9

**Comment by Synthoid** [comment]
Maybe it has to do with the `Spliced Sprite` node somehow? I'll check when the new release is out 👍

**Comment by Synthoid** [comment]
Looks like the 1.0.9 update fixed these issues. All sprites and shadows are present in the correct order. Nice work!

![RainbowRunSheet](https://user-images.githubusercontent.com/6645950/211204807-a4251fbc-5e36-4fa1-a1ea-be380432fa9c.png)
