### ISSUE TITLE
[Bug] (1.0.8) - Maximizing/Minimizing Window Breaks Solid Node

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#20]
This one is a little difficult to reliably reproduce. When maximizing or minimizing the Pixel Composer window, `Solid` nodes will occasionally break. It doesn't happen every time the window is resized, but it does *usually* happen when the window is resized. Specifically, this only seems to happen **when using the maximize button for the window**, not when resizing the window by dragging its bounds. Adjusting the Color value for the node seems to fix the issue.

***Default Window:***
![image](https://user-images.githubusercontent.com/6645950/210266047-52978948-d9c4-4647-aec8-a7116a3cf447.png)

***After Maximizing Window:***
![image](https://user-images.githubusercontent.com/6645950/210266112-b1c8cfb9-adef-4468-88dc-c1dcd2fae52a.png)

**Comment by Ttanasart-pt** [comment]
Okay, I'll look into this one. This kind of bug can happen all the time since surfaces are store in VRAM. I've put fail safe in the earlier version but it seems some still slip through.

**Comment by Synthoid** [comment]
This issue seems to be fixed as of `1.0.9`? I'll leave this open in case you have some tests you are still working on, but I haven't been able to recreate the issue.

**Comment by Ttanasart-pt** [comment]
I'm still not sure if I cover every case, but we can close it for now.
