### ISSUE TITLE
[Bug] (1.0.9) - Setting Solid Node Dimension to (1, 1) Doesn't Update Node Dimensions

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#22]
Attempting to set a `Solid` node's dimensions to (1, 1) will not update the output resolution of the node. Adjusting one value to 1 seems to work fine, but setting the second value to 1 will preserve the previous output resolution. Adjusting from (1, 1) to any higher value works as expected. For example:

Initial Resolution | New Resolution | Output Resolution | Status
------------------ | ----------------- | -------------------- | -------
(2, 2) | (2, 1) | (2, 1) | ✅
(2, 2) | (1, 2) | (1, 2) | ✅
(1, 2) | (1, 1) | (1, 2) | ❌
(1, 1) | (2, 1) | (2, 1) | ✅

![image](https://user-images.githubusercontent.com/6645950/211207710-321059c0-f521-4c01-a1c5-5c2aa5d62daf.png)

**Comment by Ttanasart-pt** [comment]
That's... interesting. I'll look into it.

**Comment by Synthoid** [comment]
Nice, seems like the `1.1.0` release fixed this issue!

![image](https://user-images.githubusercontent.com/6645950/213068589-e4144a75-faea-4402-8b3c-a4ef19e06758.png)
