### ISSUE TITLE
[Enhancement] - Tab Based Field Navigation

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#23]
Currently, you must use the mouse to click on each field to begin editing it. It would speed things up a lot if you could use the `Tab` key to jump to the "next" logical field, relative to your currently active field. I know you wrote the UI for this yourself so this is probably a bit of a lift on your end but it would be a huge UX improvement.

![image](https://user-images.githubusercontent.com/6645950/211209578-68819339-650e-4aaf-9049-b7de1bd45853.png)

**Comment by Ttanasart-pt** [comment]
Oh, I've planning to implementing this for a long time now but I forgot. Thanks for your suggestion/reminder!

**Comment by Synthoid** [comment]
Playing with the 1.1.0.1 release currently and the tab navigation is super nice! Much easier to flow from field to field now. I did notice that the `Splice sprite` node flow is a little odd. Specifically, the padding flows from link axis to right padding, to top, left, and finally bottom:

***Current flow:***
![image](https://user-images.githubusercontent.com/6645950/213067459-42e1406f-39d7-402c-b41f-071de728955b.png)

I would expect the flow to generally flow from topmost left to bottommost right.

***Expected flow:***
![image](https://user-images.githubusercontent.com/6645950/213067849-32f5390d-0f33-4d67-bb92-2dfc396f4c48.png)

This is a small issue though. Just having tab navigation greatly speeds up working!

**Comment by Ttanasart-pt** [comment]
That's true. The padding data is defined as counter-clockwise start from right (0 degree) so the navigation follow that. I can change it in the next version.
