### ISSUE TITLE
[Enhancement] Reveal Assets After Export Process

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#24]
It would be nice if the OS opened a file explorer window for the folder containing assets generated during an export process. In other words, clicking the `Execute node` button on an `Export` node would export the desired files, then open a file explorer window at the export location. This isn't a critical issue, but it would be a good UX improvement as it cuts down on time when exporting files to folders you don't have open already.

![image](https://user-images.githubusercontent.com/6645950/211677722-69ca4d1c-2e46-4e78-b8f1-fb321f072204.png)

![image](https://user-images.githubusercontent.com/6645950/211678062-3a42a617-0749-4f1f-b484-c4c630c6b254.png)

**Comment by Synthoid** [comment]
Ah, that is handy. I should have read the release notes more closely...

I didn't even notice those notifications. Maybe when you finish exporting, an "Export Complete" notification can be forcibly shown briefly? Then that can be clicked on to open the folder location? Now that I know about the export notifications, this isn't too bad of an issue. I'm just thinking about making it intuitive for new users. 🤔

**Comment by Ttanasart-pt** [comment]
Sure, I'll make it more obvious (may be make it blink or something) in the next version.

**Comment by Synthoid** [comment]
Nice, I think that will make it more intuitive.

Also, thanks for all the good work! It's been fun tinkering with Pixel Composer and you've been great at squashing bugs as they crop up.
