### ISSUE TITLE
[Bug?] (1.1.0.1) - Splice Sprite Node Animation Output Doesn't Update

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#25]
Outputting an Animation with a `Splice sprite` node in `1.1.0.1` doesn't seem to update sprites during animation playback. I saw in the release notes that:

```
[Splice sprite sheet] Now require manual update.
```

I did manually execute the node, which built the sheet as expected but it doesn't animate. I'm not sure if this is the expected behavior now or if I'm just missing a new step. Outputting an Array then passing that into a `Sequence to Anim` node seems to update everything as expected.

![image](https://user-images.githubusercontent.com/6645950/213072325-1409d54a-e259-4157-b36b-5bc896de6263.png)

**Comment by Ttanasart-pt** [comment]
That's not an expected behaviour. Thanks for reporting.

**Comment by Synthoid** [comment]
Seems to be fixed in `1.11.0`
