### ISSUE TITLE
[Enhancement] Blend Node Output Size Controls

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#27]
Currently, a `Blend` node's output resolution seems to be solely based on the `Background` input. It would be nice to have an option to either:

- Specify which input to pull output resolution from (background, foreground, or mask)
- Declare output size as relative to input (current behavior) or absolute (user can set the output size)

Then a scale operation (or some other cheap and fast operation) could be applied to non-resolution matching inputs.

***48x48 Background Input***
![image](https://user-images.githubusercontent.com/6645950/213079935-2c6ff4bf-146f-4e60-bd41-2a902e22fb6f.png)

***1x1 Background Input***
![image](https://user-images.githubusercontent.com/6645950/213080034-fc58a965-d668-4662-94c5-d0437151e2f0.png)

This is mostly a best practice pulled over from my experience with Substance Designer. There it is much cheaper to work with `8x8` solid textures than `1024x1024` (or larger) solid color textures. I'd assume that a similar principal would be true here as well, with a `2x2` node being cheaper memory wise than a `32x32` node. Granted, Pixel Composer sizes are probably much smaller on average and therefore not as taxing so this may not really be much of a performance issue ever.

Even so, supporting more flexible blend output sizes would help speed up workflows since we wouldn't need specifically sized `Solid` nodes during blend operations.

**Comment by Ttanasart-pt** [comment]
Thanks for your suggestion. I agree with you on the convenience side since I found myself adding scale and padding node a bit too often in the past as well.

**Comment by Ttanasart-pt** [comment]
Added in 1.11.
