### ISSUE TITLE
[Bug] (1.1.0.1) Color Selector Tab Navigation Flow

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#28]
Tab navigation in the `Color selector` window does not navigate as expected. Instead of flowing from top to bottom inside the color window, pressing tab navigates to the first field in the node inspector:

![image](https://user-images.githubusercontent.com/6645950/213901267-6d9488c2-2323-46c4-97c1-36a46cee252d.png)

The solid line is the current navigation flow and the dotted line is the expected flow.

**Comment by Ttanasart-pt** [comment]
I didn't implement tab navigation in the popup dialogs yet. Will add in the next version.

**Comment by Synthoid** [comment]
Added in 1.11.0
