### ISSUE TITLE
[Enhancement] PXC Project Meta Data

### ISSUE THREAD

**Issue by Synthoid** [Ttanasart-pt/Pixel-Composer#31]
It would be nice if `.pxc` files supported some optional meta data for things like project description, author name and website URL, etc. As Pixel Composer grows and users start sharing example projects this would be very helpful in drawing eyes back to artists creating cool and interesting projects.

Here's an example of the kinds of meta data supported by Substance Designer:

![image](https://user-images.githubusercontent.com/6645950/214742322-88062714-8011-4d77-bb43-a6a38ee67237.png)

A good interaction for accessing this meta data would be to double click on an empty space anywhere in the graph window. Meta data could also be shown in the inspector by default when loading a project.

**Comment by Ttanasart-pt** [comment]
That's a good idea. Making it appear when start a project sound right. Double click on empty space... can work. I'll implement it in the version.

**Comment by Ttanasart-pt** [comment]
Added in 1.12
