### ISSUE TITLE
[BUG] Left click not workingas expected

### ISSUE THREAD

**Issue by xalixilax** [Ttanasart-pt/Pixel-Composer#32]
I've encountered an issue where I was not able to properly interact with the global screen. Trying to link node just move the screen and opening group with a double click doesn't work either. Left click also just move the screen instead of moving the node. Right click seems to work as intended. Space bar does not start/stop animation. 

This seems to happen when you right click and while keeping the menu open you alt+tab. I managed to make it work again by right clicking and node and doing alt+tab only another app. 

I managed to reproduce it more than once. To make it happen, only a right click and alt+tab seems to broke it. For it to work again, it seems like you need to open an app OVER Pixel Composer.

**Comment by Ttanasart-pt** [comment]
Okay, I've got a report about this problem before. I'm looking into it.
