### ISSUE TITLE
[Interest Check] Godot port?

### ISSUE THREAD

**Issue by IcedQuinn** [Ttanasart-pt/Pixel-Composer#33]
Would there be any interest in a Godot port?

There are some similar tools (Pixelorama, Material Maker) with similar licenses to borrow from and many of the UI components also exist over there. It would open up some Linux and possibly Mac opportunities as well.

**Comment by Ttanasart-pt** [comment]
I don't know Godot, so no. Also Linux and Mac port is possible in GameMaker. I'm just waiting for the paycheck so I can buy a hardware to do it.
