### ISSUE TITLE
The Particle Node is Broken (1.13)

### ISSUE THREAD

**Issue by TheShankar** [Ttanasart-pt/Pixel-Composer#35]
I've noticed that none of the Groups/Nodes that depend on the Particle System (like Rain) are working,

I've also tested the Tutorial Number 5: (Particle and Effectors) and it seems like the Particles also aren't working there, when previewing all you get is a blank screen.

I'm running on Windows 10, version 1.13 Steam. Tried to reinstall it and also tested the 1.13 non steam demo. Same issue.

I've also tested the Free version here (0.8.2) and the Particle Node works fine there.

**Comment by Ttanasart-pt** [comment]
Did you connect any image to the input value in the rain collection? If you didn't give it original image, you won't see anything.

![image](https://user-images.githubusercontent.com/22589759/221090595-2ac5b5d9-4d8e-4202-92b7-fc58ac2bfadf.png)

And the tutorial is on the older version, I'll update it, thank for reporting.

**Comment by TheShankar** [comment]
Thank you for fixing! it looks like everything is working properly now, both the tutorial and the particle node!

Much love.
