### ISSUE TITLE
Crash on Rendering/Execute all export nodes

### ISSUE THREAD

**Issue by don1ck** [Ttanasart-pt/Pixel-Composer#36]
Hi, got a crash on "Rendering/Execute all export nodes" operation. (steam v1.13.1)
My graph is pretty simple, outliner with export node.

Crash log:

```
-------------------------- OH NO --------------------------


ERROR in
action number 1
of Draw Event
for object o_dialog_menubox:


Unable to get variable initExport from object 000001C9C2909500

gml_Script_anon_Panel_Menu_gml_GlobalScript_panel_menu_59611125_Panel_Menu_gml_GlobalScript_panel_menu
-------------------------- STACK TRACE --------------------------

gml_Script_anon_Panel_Menu_gml_GlobalScript_panel_menu_59611125_Panel_Menu_gml_GlobalScript_panel_menu (line 132)
gml_Object_o_dialog_menubox_Draw_64 (line 35)

---------------------------- :( ----------------------------

```

**Comment by don1ck** [comment]
![PixelComposer_BZus65MYqp](https://user-images.githubusercontent.com/1050454/221290279-bd451c4c-35f4-413e-a4e7-9c3153ebc053.png)
Graph, but looks like the problem is not the graph )

**Comment by Ttanasart-pt** [comment]
I've updated 1.13.2 on itch, steam beta branch which should fix this problem now.

**Comment by don1ck** [comment]
Thank you, waiting for the stable branch on steam
