### ISSUE TITLE
Loop Index on Loop Array not properly working, also general issues with Arrays, Loops and Render Cache/Spritesheet

### ISSUE THREAD

**Issue by TheShankar** [Ttanasart-pt/Pixel-Composer#41]
Here is a sample:
General View:
![image](https://user-images.githubusercontent.com/46303245/222550573-dfcbdedf-dc6e-49f8-8032-85a2812ea093.png)

Inside the Array Loop:
![image](https://user-images.githubusercontent.com/46303245/222551263-70033f6c-928b-4e96-9cbd-54c912eabab2.png)

In theory, what I think should happen is: 
Array[1] gets blended with Array[0]
Array[2] gets blended with Array[1]

But Loop Index is just stuck to a singular number, sometimes it's 0 (first loop), sometimes it's 4(last loop). I've had this same problem with both Loop Array and just the Normal Loop.
Here is the file: 
[Buggy But Doesn't Crash.zip](https://github.com/Ttanasart-pt/Pixel-Composer/files/10875780/Buggy.But.Doesn.t.Crash.zip)

I'm also having tons of different issues with "Silent Bugs" on Arrays and related things like Loops, Cache Array, Render/Split Spritesheet and whatnot. Here is a file:
[Silent Buggy.zip](https://github.com/Ttanasart-pt/Pixel-Composer/files/10875796/Silent.Buggy.zip)

In theory, this file is a previous attempt at doing the same effect as "buggy but don't crash", but something has "silent bugged" around the way, meaning I didn't get an error message, but things stopped working. Now the file is "cursed", if you try to open it you may get an error message or nothing, but the Loop Array node won't work anymore:
![image](https://user-images.githubusercontent.com/46303245/222554962-77fd6f84-4ed6-46a9-b112-62e6c48fbde4.png)

Here is the bug I get sometimes:
![image](https://user-images.githubusercontent.com/46303245/222555736-ceb22c43-890b-4b65-bffa-6ea982f6ec70.png)

I had other bugs in different files, the messages change.

Maybe we could get a "Refresh Everything" button? feels like many of these bugs are because there are bugged connections and general issues, that somewhat are still present in the save file and/or memory. If we could flush all the caches and have Pixel Composer recreate the node connections from the "scratch", it could be solved?

**Comment by Ttanasart-pt** [comment]
To send in data between group. You should use the dedicated group input / output node. As tunnel break rendering order, it should only be use in the same context (Tunnel node is a organizing tool, not flow control).

This node setup should give you the result you want.
![image](https://user-images.githubusercontent.com/22589759/222648155-846e2e42-fde5-4ac0-a127-71502dd5e027.png)
![image](https://user-images.githubusercontent.com/22589759/222648175-c6ef79a2-e67a-4a4a-8a70-ee1607cd8fb6.png)

**Comment by TheShankar** [comment]
Thank you! I was using the tunnel in/out because for whatever reason adding a new loop input wasn't working. Probably something bugged in my end and I didn't realize.

Thank you anyway, it's working fine now!
