### ISSUE TITLE
Small bugs on Palette Gradient Trim and Request

### ISSUE THREAD

**Issue by TheShankar** [Ttanasart-pt/Pixel-Composer#43]
Bug: On the Palette Node, the trim range works perfectly if you trim the end (from 1 to 0), but if you do it from 0 to 1, what happens is that colors become black instead of disappearing, like the ending.
![image](https://user-images.githubusercontent.com/46303245/222844004-a9098459-a969-4173-a40b-da0ff2bfba08.png)

Bug: Gradient Shift with Loop resets to Hard Blend/Bugs when looping, from -1 to 0 it works normally, from 0 to 0.5 it replaces with hard blend or the colors are simply missing, from 0.5 onwards everything disappears
![image](https://user-images.githubusercontent.com/46303245/222844665-25e77e4f-eeea-411c-b916-5e0c23954837.png)

Possibly bug: If you link a Palete node to the Gradient In node, it only samples the first color. Not sure if it's intended? 
![image](https://user-images.githubusercontent.com/46303245/222844068-b9b9712e-13e0-442f-9f46-ae38600fac04.png)

Request: And would it be possible to implement a Palette Shift, like the Gradient Shift? So we could do rotate palette effects? 

As always, thank you!

**Comment by Ttanasart-pt** [comment]
Thank you for your suggestion. I've fix the first two problem, the patch will come in the 13.7 update, As for the third one, in 1.13.5 I've added a "palette to gradient" node for that, so you might want to update first.
