### ISSUE TITLE
Crash with Water to Lava Sample project

### ISSUE THREAD

**Issue by rowanthemodder** [Ttanasart-pt/Pixel-Composer#5]
# Steps to Reproduce
- Open Water to Lava Sample project
- Crash
# Log
<details>
  <summary>Click to expand!</summary>
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object o_dialog_splash:

ds_map_exists argument 1 incorrect type (undefined) expecting a Number (YYGI32)############################################################################################
gml_Script_ds_map_try_get (line 0)
gml_Script_anon_NodeValue_gml_GlobalScript_node_value_25612305_NodeValue_gml_GlobalScript_node_value (line 962)
gml_Script_anon_Node_Composite_gml_GlobalScript_node_composite_10117170_Node_Composite_gml_GlobalScript_node_composite (line 336)
gml_Script_anon_Node_gml_GlobalScript_node_data_1313486_Node_gml_GlobalScript_node_data (line 504)
gml_Script_nodeLoad (line 210)
gml_Script_load_deserialize (line 62)
gml_Script_LOAD_PATH (line 164)
gml_Script_anon_gml_Object_o_dialog_splash_Create_0_1347331_gml_Object_o_dialog_splash_Create_0 (line 79)
gml_Script_draw_scrollPane_gml_GlobalScript_scrollPane (line 46)
gml_Object_o_dialog_splash_Draw_64 (line 49)
</details>

# Versions
- Pixel Composer 8.1

**Comment by Ttanasart-pt** [comment]
Sample projects are created in .6 version and a lot changed since then. I'll update the sample projects after version .9 (since that version will also change lot of things) so I will mark these issues as closed for now. In the next release (.8.2) I will just remove sample projects that doesn't work. Thank you for reporting in.
