### ISSUE TITLE
Purchase window does not appear

### ISSUE THREAD

**Issue by MrSdows** [Ttanasart-pt/Pixel-Composer#51]
I live in Russia and perhaps the reason is in my location, but when buying, it doesn’t redirect me anywhere, but this window remains: 
![image](https://github.com/Ttanasart-pt/Pixel-Composer/assets/126389963/4e48493a-40bb-49c5-a539-3a7686e3c74b)
I am not receiving any message in my email.

**Comment by Ttanasart-pt** [comment]
Did you already paid for it? I'm not sure what's happening either. I found similar post on itch forum from 11 days ago https://itch.io/t/3069671/payment-from-russia so it could be the store problem.

**Comment by MrSdows** [comment]
Do I understand correctly that I won't be able to buy Pixel Compositing anytime soon as the problem has been persisting for a few days now.

**Comment by Ttanasart-pt** [comment]
That's seems to be the case for now. It look like Steam and GOG also isn't available in Russia, I'm very sorry for the inconvenience.

**Comment by MrSdows** [comment]
Well, I'll keep trying to buy the Pixel Composer anyway, thanks.
