### ISSUE TITLE
Crash when pressing control +  g when a node in a loop group is selected

### ISSUE THREAD

**Issue by Nrosa01** [Ttanasart-pt/Pixel-Composer#66]
Let's say I select both array get and outline

![image](https://github.com/Ttanasart-pt/Pixel-Composer/assets/62796415/f9673730-8acb-4c21-88a8-30a54ac24c09)

If I press control + g...

![image](https://github.com/Ttanasart-pt/Pixel-Composer/assets/62796415/b61d63c1-9adc-4b9c-8e7f-72fcc431c0c8)

This happens no matter if the node is part of the loop or not

**Comment by Nrosa01** [comment]
The stack trace:

-------------------------- Pixel Composer 1.17.1.2 Crashed --------------------------

ERROR in
action number 1
of  Step Event0
for object o_main:


Unable to get variable members from object 000001468152CB00

gml_Script_groupNodes

-------------------------- STACK TRACE --------------------------

gml_Script_groupNodes (line 17)
gml_Script_doGroup@Panel_Graph@panel_graph (line 2220)
gml_Script_panel_graph_group (line 69)
gml_Object_o_main_Step_0 (line 48)




-------------------------- Device Info --------------------------

Version: 1.17.1.2 (11712)
Operating system: Windows (655360)

---------------------------- :( ----------------------------

**Comment by Ttanasart-pt** [comment]
noted, thanks for reporting.

**Comment by Nrosa01** [comment]
This seems to be fixed in the latest beta (1.17.6 steam) so I'm closing this issue. I didn't expect this getting fixed that fast. Thank you!
