### ISSUE TITLE
Bug on update 1.18.0.3 (repeat component)

### ISSUE THREAD

**Issue by loudoweb** [Ttanasart-pt/Pixel-Composer#78]
I tried to reopen a file I've made few weeks ago but now with version 1.18.0.3 this issue occurs. Maybe it has something to do with the **repeat** node (because I update the amount component in first frame).

![image](https://github.com/user-attachments/assets/dc79a648-4180-45f8-8cba-5dfec3fda552)

This error prevents anything to display in my nodes and my preview.

How can I help you solve this issue? Do you need the file?

**Comment by Ttanasart-pt** [comment]
Oh, it's just a really bad typo on the code. I'll release the patch soon.

**Comment by Ttanasart-pt** [comment]
Should be fixed in 1.18.0.4 now
