### ISSUE TITLE
[BUG] Array Node Forgets Inputs

### ISSUE THREAD

**Issue by babyblueboxers** [Ttanasart-pt/Pixel-Composer#9]
### **Log message**
Not applicable, as no crash occurs.

### **Describe the bug**
When loading a saved project, the Array node will only have a connection to the first input slot. It "forgets" other inputs were attached, and defaults to 4 inputs slots, 3 of which are unconnected.

### **To Reproduce**
1. Create two Number nodes.
2. Create and Array node.
3. Connect each Number node to a slot in the Array node.
4. Save the project.
5. Reload the project.

### **Expected behavior**
The array node should retain attached values.

### **System**
 - Version 1.0.1
 - Windows 11

### **Additional context**
None needed.

**Comment by Ttanasart-pt** [comment]
Noted, definitely need to look into dynamic node (node with any number of inputs) a bit more.

**Comment by Ttanasart-pt** [comment]
Fixed in 1.0.2
